### PR TITLE
fix: vue file imports order

### LINKED ISSUE #1127: Imports are not placed at the top of the file when TypeScript interface is present for `vue`
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&inputTab=FYZwHkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4AiAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFChIsOABV0qeCTJwA5DDkxlo8QDs1UIgEMAxngCyATwDCZSNvS6ACqTCpEouHCMALRkyj2ALjgDbXNRfC10AA9JeBZDZAYFZG0jGE5tOAtrcAg7XQAKMGdUIOybPPsYJwgXAEo3DyM8+Th5AzU4AF4UDGxcAoR3DzhtAxB0IIpsdAA3dAoAGmGmiAZoIOV/Jk0PfDqxD2H/GGQoTIKVuAAeJmBZgD4rj2vgbTBkGGeRo1RULoQQxGwJ+aw2lG2S2+ewiIJGswMDGQ6AB7TUbDGE1hcLgeUsXhCAHMUQgCnMqg0ug9EG0YB10BjxngeuTdGw6VBiTA2AikXh8NjgVwnnCABLoBjrb4INEMzHofAAQjgAElPCE4FAUnA3nAAEroYwwRZwABqyJNmDWwCYJugcAAMsAAI70JiK6XFWqoNjeXz+bSCm5cO6PYYHcJAA%3D%3D

### Expected Behaviour

When an import and an interface are present, like in the following example:
```tsx
import { useStore } from "@builder.io/mitosis";
import Test from './test.lite'

interface MyComponentProps {
  children: any
}

export default function MyComponent(props: MyComponentProps) {
  const state = useStore({
    name: "Steve",
    color: 'red'
  });
  
  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={state.name}
        onChange={(event) => { state.name = event.target.value }}
      />
      Hello
      {state.name}! I can run in React, Vue, Solid, or Liquid!
      {props. children}
    </div>
  );
}
```
for the vue target, the compiler should place the imports at the top of the file, like in the following output example:

```tsx
<template>
  <div>
    <input class="input" :value="name" @input="name = $event.target.value" />
    Hello
    {{ name }}! I can run in React, Vue, Solid, or Liquid!
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import Test from "test";

interface MyComponentProps {
  children: any;
}

const props = defineProps<MyComponentProps>();
const name = ref("Steve");
const color = ref("red");
</script>

<style scoped>
.input {
  color: red;
}
</style>
```

### Actual Behaviour

When an import and an interface are present, like in the following example:
```tsx
import { useStore } from "@builder.io/mitosis";
import Test from './test.lite'

interface MyComponentProps {
  children: any
}

export default function MyComponent(props: MyComponentProps) {
  const state = useStore({
    name: "Steve",
    color: 'red'
  });
  
  return (
    <div>
      <input
        css={{
          color: "red",
        }}
        value={state.name}
        onChange={(event) => { state.name = event.target.value }}
      />
      Hello
      {state.name}! I can run in React, Vue, Solid, or Liquid!
      {props. children}
    </div>
  );
}
```
for the vue target, the compiler should place the imports at the top of the file, but it doesn't, like in the following example:

```tsx
<template>
  <div>
    <input class="input" :value="name" @input="name = $event.target.value" />
    Hello
    {{ name }}! I can run in React, Vue, Solid, or Liquid!
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
interface MyComponentProps {
  children: any;
}

import Test from "test";

const props = defineProps<MyComponentProps>();
const name = ref("Steve");
const color = ref("red");
</script>

<style scoped>
.input {
  color: red;
}
</style>
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ohkimur**
## Description

This PR closes #1127

### CODE REVIEW

File: packages/core/src/generators/vue/vue.ts [hunk 1]
```diff
@@ -1,37 +1,37 @@
+import { flow, pipe } from 'fp-ts/lib/function';
```
Comment (samijaber) [inline packages/core/src/generators/vue/vue.ts:1]: Can you disable your import auto-sort in your IDE? It makes it much harder to read the changes in PRs.

**Comment by ohkimur** [comment]
@samijaber I reverted the imports order.

**Review by samijaber — APPROVED** [review]
🏆
