### PR TITLE
fix: #700 vue3 composition api does not add computed

### LINKED ISSUE #700: Vue 3 composition-api  do not use computed
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNroDRwQB2AqmACYCGM6cAvnAGZQQhwBEAAgEbLAA25dFAB0wCAHoQwHKmCp2AbgBQy9AA9IsOEMaVk%2FeI2REAxjHFE4AWQCeAYVaQi6IjAAUYFmFQBKRMpwcKbEqPBh1LQAvCgY2LjuCIFBcESUIOgAXBzY6ABu6Ox4yUEA5ujwaOgACt7u%2FkkpKVAVyFBWXhA%2BImkZcAA%2B%2FXAA5Lr6hgBqlPzI6MMl9Ml0vipByS0wbVbuCwA85MB5AHwLQbvARGDIMKcppqioUQiNTa8h%2FNDZ7C3kRbdBdDo%2FzgeWmsyeERoPXS6CBrxSxHsAAtKERyk93PlXDB%2FFEjog4JD0NC%2BjEsW4RDBKFByjARKCZrRAbcJCd4QAJdD8D63BBEkRVWpdOgAQjgAElgqi4FATHALnAAEroSjmAgTWYETAQfjAcgEaBwAAywAAjnxyCK9hIDsdkitlHQgA

### Expected Behaviour

when using `useStore` `get` should produce `computed` https://vuejs.org/api/reactivity-core.html#computed reactive variable

### Actual Behaviour

Not render at all `get` state

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by raymondmuller**
## Description
closes #700

### CODE REVIEW

File: packages/core/src/generators/vue.ts [hunk 1]
```diff
@@ -929,6 +950,7 @@ const componentToVue: TranspilerGenerator<ToVueOptions> =
       component.hooks.onMount?.code && vueImports.push('onMounted');
       component.hooks.onUnMount?.code && vueImports.push('onUnMounted');
       onUpdateWithoutDeps.length && vueImports.push('onUpdated');
+      size(getterKeys) && vueImports.push('computed');
```
Comment (samijaber) [inline packages/core/src/generators/vue.ts:953]: Shouldn't this be a vue3 import only? i.e. wrapped in a `if (options.vueVersion >= 3)` check?

I think that might be the case for some other imports as well like `watch` and `ref`.

Comment (raymondmuller) [reply packages/core/src/generators/vue.ts:953]: Composition API is available in Vue 2 (since 2.7) as well and this is wrapped in a `if (options.api === 'composition)`

**Comment by samijaber** [comment]
Just need to update snapshots after we merged your other PR @raymondmuller

**Review by samijaber — APPROVED** [review]
