### PR TITLE
fix(core): #832 handle arrow functions within objects

### LINKED ISSUE #832: Svelte: cannot process anonymous functions in store
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [X] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=M4NwpgNgLmQ%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4AiAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFCj0AD0iw4LIgENkDeEWQA7AMYxO6uAFkAngGEykdenUwAFGFJhUASkSi4cTRHWp43hTDwAvCgY2LjWCK5ucOoKIOgAXHAA5N7oAG7oSQA0kW4YMABysejWaQoMyOjOEVFRvv5sMXFwQWUV6GK1%2BDm1%2BUVxAEyJbZUtAHwutXkwfuiNxS1wI%2Bi5BHCR%2BI5ikVDoMMhQetarADxMwGljq24AEugMDBCI9XNN6PinXOeXkVui%2BEA%3D%3D%3D

### Expected Behaviour

```html
<script>
  function setName(value) {
    name = value;
  }

  function setName2(value) => {
    name = value;
  };

  let name = "steve";
</script>

<div>
  Hello {name}
</div>
```

### Actual Behaviour

```html
<script>
  function setName(value) {
    name = value;
  }

  (value) => {
    name = value;
  };

  let name = "steve";
</script>

<div>
  Hello {name}
</div>
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by raymondmuller**
## Description
Fixes #832 

This is currently an issue in other frameworks as well (such as React and Solid).
Converting an arrow expression inside an object property to an object method seems to solve it.

Also fixed a typo in this PR (tarverse > traverse)

Before:

Screenshot 2022-11-04 at 15 52 54
Screenshot 2022-11-04 at 15 53 01

After:
832-solid
832-react
832-svelte

### CODE REVIEW

File: packages/core/src/helpers/traverse-nodes.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { MitosisNode } from '../types/mitosis-node';
 import traverse, { TraverseContext } from 'traverse';
 import { isMitosisNode } from './is-mitosis-node';
 
-export function tarverseNodes(
+export function traverseNodes(
```
Comment (samijaber) [inline packages/core/src/helpers/traverse-nodes.ts:6]: what's wrong with `tarverse` 😄

**Review by samijaber — COMMENTED** [review]
Sweet! Could we add an arrow function to a snapshot test to show it working now?

**Comment by raymondmuller** [comment]
@samijaber added a snapshot test which includes an arrow function inside useStore ✅

**Review by samijaber — APPROVED** [review]
